/****************************************************************************
 * Copyright (C) 2014, <Copyright Holder>                                   *
 * All rights reserved                                                      *
 *                                                                          *
 * For the licensing terms see LICENSE file inside the root directory.      *
 * For the list of contributors see AUTHORS file inside the root directory. *
 ***************************************************************************/
#ifndef SRC_APPINFO_H_
#define SRC_APPINFO_H_

/** AUTO-GENERATION WARNING:
 *  This file has been automatically generated from "appinfo.h.in.cmake".
 *  DO NOT edit this file, as any changes will be automatically discarded. */

#define APPLICATION_NAME               "HostMe Agent"
#define APPLICATION_CODENAME           "hostme"
#define APPLICATION_COPYRIGHT_YEARS    "2018"
#define APPLICATION_VERSION_MAJOR      1
/* #undef APPLICATION_VERSION_MINOR */
/* #undef APPLICATION_VERSION_PATCH */
#define APPLICATION_VERSION_TYPE       "SNAPSHOT"
#define APPLICATION_VERSION_STRING     "1.0.0-SNAPSHOT"
#define APPLICATION_VENDOR_ID          "com.hostme"
#define APPLICATION_VENDOR_NAME        "HostMe"
#define APPLICATION_VENDOR_URL         "hostme.fr"
#define APPLICATION_ID                 "com.hostme"

#ifndef APPLICATION_NAME
#   error "Please specify the application name in CMakeLists.txt."
#endif

#ifndef APPLICATION_CODENAME
#   error "Please specify the application codename in CMakeLists.txt."
#endif

#ifndef APPLICATION_COPYRIGHT_YEARS
#   error "Please specify the application copyright years in CMakeLists.txt."
#endif

#ifndef APPLICATION_VERSION_MAJOR
#   define APPLICATION_VERSION_MAJOR 0
#endif

#ifndef APPLICATION_VERSION_MINOR
#   define APPLICATION_VERSION_MINOR 0
#endif

#ifndef APPLICATION_VERSION_PATCH
#   define APPLICATION_VERSION_PATCH 0
#endif

#ifndef APPLICATION_VERSION_TYPE
#   define APPLICATION_VERSION_TYPE "SNAPSHOT"
#endif

#ifndef APPLICATION_VENDOR_ID
#   error "Please specify the application vendor id in CMakeLists.txt."
#endif

#ifndef APPLICATION_VENDOR_NAME
#   error "Please specify the application vendor name in CMakeLists.txt."
#endif

#ifndef APPLICATION_VENDOR_URL
#   error "Please specify the application vendor URL in in CMakeLists.txt."
#endif

#ifndef APPLICATION_ID
#   define APPLICATION_ID APPLICATION_VENDOR_ID "." APPLICATION_CODENAME
#endif

#endif
